version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: 
       # Install our python package before building the docs
      install:
        - method: pip
          path: .
    
sphinx: "3.8"
  fail_on_warning: true

formats:
  - pdf
  - epub
